"""Export MMTL results as an HSPICE W-element RLGC model.

The original TNT wrote a ``<name>.hspice-w.rlgc`` file.  That Tcl source is not
in this repository, so the exact byte layout cannot be reproduced verbatim; we
emit the standard HSPICE W-element RLGC file format (lower-triangular L, C, Ro,
Go, Rs, Gd matrices) and compute the resistance terms from the equations in the
TNT user guide:

    Ro = R_DC = 1 / (sigma * Area)                (ohm/m)
    Rs = sqrt(pi * mu0 / sigma) / Circumference   (ohm/(m*sqrt(Hz)))   [skin]

L0 and C0 are copied directly from MMTL's inductance and electrostatic
induction matrices; Go and Gd are zero (BEM MMTL is loss-free).
"""

from __future__ import annotations

import math

from pymmtl import units
from pymmtl.geometry import conductor_area, conductor_circumference
from pymmtl.model import CrossSection
from pymmtl.results import Results


def _resistance_terms(cs: CrossSection, names: list[str]):
    """Return (Ro, Rs) lists aligned with ``names`` from geometry + conductivity."""
    geo = cs.resolve()
    by_name = {c.name: c for c in geo.conductors if not c.is_ground}
    ro, rs = [], []
    for nm in names:
        c = by_name.get(nm)
        if c is None or c.conductivity <= 0.0:
            ro.append(0.0)
            rs.append(0.0)
            continue
        area = conductor_area(c)
        circ = conductor_circumference(c)
        ro.append(1.0 / (c.conductivity * area) if area > 0 else 0.0)
        rs.append(
            math.sqrt(math.pi * units.MU0 / c.conductivity) / circ
            if circ > 0
            else 0.0
        )
    return ro, rs


def _lower_triangle(matrix, n: int, diag=None) -> list[str]:
    """Format the lower triangle of an n*n matrix (or a diagonal-only vector)."""
    lines = []
    for i in range(n):
        row = []
        for j in range(i + 1):
            if matrix is not None:
                row.append(f"{matrix[i][j]:.10e}")
            else:
                row.append(f"{diag[i]:.10e}" if i == j else "0.0000000000e+00")
        lines.append(" ".join(row))
    return lines


def hspice_w_element(cs: CrossSection, res: Results, title: str | None = None) -> str:
    """Return the text of an HSPICE W-element RLGC model for this cross-section."""
    names = res.names
    n = len(names)
    ro, rs = _resistance_terms(cs, names)
    title = title or cs.title or "pymmtl"

    out: list[str] = []
    out.append(f"* HSPICE W-element RLGC model generated by pymmtl")
    out.append(f"* Cross-section: {title}")
    out.append(f"* Conductors ({n}): {', '.join(names)}")
    out.append("* Per-unit-length matrices (SI: H/m, F/m, ohm/m, S/m).")
    out.append("* Lo and Co are copied from MMTL; Go = Gd = 0 (loss-free).")
    out.append("")
    out.append(f"{n}")

    out.append("* Lo (H/m)")
    out += _lower_triangle(res.L, n)
    out.append("* Co (F/m)")
    out += _lower_triangle(res.C, n)
    out.append("* Ro (ohm/m)")
    out += _lower_triangle(None, n, diag=ro)
    out.append("* Go (S/m)")
    out += _lower_triangle(None, n, diag=[0.0] * n)
    out.append("* Rs (ohm/(m*sqrt(Hz)))")
    out += _lower_triangle(None, n, diag=rs)
    out.append("* Gd (S/(m*Hz))")
    out += _lower_triangle(None, n, diag=[0.0] * n)
    out.append("")
    return "\n".join(out)


def write_hspice_w_element(cs: CrossSection, res: Results, path) -> None:
    with open(path, "w") as fh:
        fh.write(hspice_w_element(cs, res))
